//Standard basic libraries
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <boost/multiprecision/cpp_int.hpp>
#include <cmath>
//Mapping of canonical names to registers
#include "program_structure/Rregdict.cpp"

using namespace boost::multiprecision;

//Utility programs which facilitate in computing the outputs
#include "utils/str2bin.cpp"
#include "utils/bindec.cpp"
#include "utils/usgnbindec.cpp"
#include "utils/bitlogic.cpp"
#include "utils/printreg.cpp"
#include "utils/Mem.cpp"
#include "utils/printmem.cpp"
#include "utils/binhex.cpp"
#include "utils/fileprintmem.cpp"
#include "utils/fileprintreg.cpp"
#include "Floating_Point_Instructions/Miscellaneous/Converter.cpp"
#include "Floating_Point_Instructions/Miscellaneous/getrounding.cpp"

//Programs associated with each opcode
#include "arith_instructions/lui.cpp"
#include "arith_instructions/auipc.cpp"
#include "arith_instructions/addi.cpp"
#include "arith_instructions/slti.cpp"
#include "arith_instructions/sltiu.cpp"
#include "arith_instructions/xori.cpp"
#include "arith_instructions/ori.cpp"
#include "arith_instructions/andi.cpp"
#include "arith_instructions/slli.cpp"
#include "arith_instructions/srli.cpp"
#include "arith_instructions/srai.cpp"
#include "arith_instructions/add.cpp"
#include "arith_instructions/sub.cpp"
#include "arith_instructions/slt.cpp"
#include "arith_instructions/sltu.cpp"
#include "arith_instructions/sll.cpp"
#include "arith_instructions/srl.cpp"
#include "arith_instructions/sra.cpp"
#include "arith_instructions/xor.cpp"
#include "arith_instructions/and.cpp"
#include "arith_instructions/or.cpp"
#include "arith_instructions/addiw.cpp"
#include "arith_instructions/slliw.cpp"
#include "arith_instructions/srliw.cpp"
#include "arith_instructions/sraiw.cpp"
#include "arith_instructions/sllw.cpp"
#include "arith_instructions/srlw.cpp"
#include "arith_instructions/sraw.cpp"
#include "arith_instructions/addw.cpp"
#include "arith_instructions/subw.cpp"
#include "arith_instructions/divs.cpp"
#include "arith_instructions/divu.cpp"
#include "arith_instructions/divw.cpp"
#include "arith_instructions/rem.cpp"
#include "arith_instructions/remu.cpp"
#include "mul instructions/mul.cpp"
#include "mul instructions/mulh.cpp"
#include "mul instructions/mulhu.cpp"
#include "mul instructions/mulhsu.cpp"
#include "mul instructions/mulw.cpp"
#include "memory_instructions/lb.cpp"
#include "memory_instructions/lh.cpp"
#include "memory_instructions/lhu.cpp"
#include "memory_instructions/lbu.cpp"
#include "memory_instructions/lwu.cpp"
#include "memory_instructions/lw.cpp"
#include "memory_instructions/ld.cpp"
#include "memory_instructions/sb.cpp"
#include "memory_instructions/sh.cpp"
#include "memory_instructions/sw.cpp"
#include "memory_instructions/sd.cpp"
#include "branch_instructions/jal.cpp"
#include "branch_instructions/jalr.cpp"
#include "branch_instructions/beq.cpp"
#include "branch_instructions/blt.cpp"
#include "branch_instructions/bge.cpp"
#include "branch_instructions/bltu.cpp"
#include "branch_instructions/bgeu.cpp"
#include "branch_instructions/bne.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FADD.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FDIV.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMADD.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMAX.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMIN.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMSUB.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMUL.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FNMADD.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FNMSUB.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FSQRT.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FSUB.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Classify/FCLASS.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Compare/FEQ.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Compare/FLE.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Compare/FLT.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.L.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.LU.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.S.L.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.SU.L.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.SU.W.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.S.W.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.W.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.WU.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FMV.S.X.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FMV.X.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FSGNJN.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FSGNJ.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FSGNJX.S.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FADD.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FDIV.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMADD.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMAX.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMIN.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMSUB.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMUL.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FNMADD.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FNMSUB.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FSQRT.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FSUB.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Classify/FCLASS.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Compare/FEQ.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Compare/FLE.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Compare/FLT.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.L.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.LU.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.D.L.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.DU.L.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.DU.W.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.D.W.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.W.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.WU.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FMV.D.X.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FMV.X.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FSGNJN.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FSGNJ.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FSGNJX.D.cpp"





